In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import pickle
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn import svm, datasets
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import sklearn
from sklearn.model_selection import train_test_split
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree

In [ ]:
!apt-get install swig -y

Reading package lists... Done
Building dependency tree
Reading state information... Done
swig is already the newest version (3.0.12-1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.

In [ ]:
!pip install cython numpy

Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (0.29.24)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.19.5)

In [ ]:
!pip install auto-sklearn

Requirement already satisfied: auto-sklearn in /usr/local/lib/python3.7/dist-packages (0.14.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.10.0.2)
Requirement already satisfied: pyrfr<0.9,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.8.2)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.14 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.4.20)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.5)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.19.5)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.7.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.0)
Requirement already satisfied: dask<2021.07 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (2021.6.2)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.0.0)
Requirement already satisfied: pynisher>=0.6.3 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.6.4)
Requirement already satisfied: smac>=0.14 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.1)
Requirement already satisfied: distributed<2021.07,>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (2021.6.2)
Requirement already satisfied: liac-arff in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (57.4.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.13)
Requirement already satisfied: scikit-learn<0.25.0,>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.24.2)
Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn) (0.29.24)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.7/dist-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn) (3.0.6)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (2021.11.1)
Requirement already satisfied: cloudpickle>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (2.0.0)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (0.11.2)
Requirement already satisfied: partd>=0.3.10 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (1.2.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (1.0.3)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (1.7.0)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (2.0.0)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (7.1.2)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (2.4.0)
Requirement already satisfied: tornado>=5 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (5.1.1)
Requirement already satisfied: psutil>=5.0 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (5.4.8)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->auto-sklearn) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->auto-sklearn) (2.8.2)
Requirement already satisfied: locket in /usr/local/lib/python3.7/dist-packages (from partd>=0.3.10->dask<2021.07->auto-sklearn) (0.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0->auto-sklearn) (1.15.0)
Requirement already satisfied: emcee>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from smac>=0.14->auto-sklearn) (3.1.1)
Requirement already satisfied: heapdict in /usr/local/lib/python3.7/dist-packages (from zict>=0.1.3->distributed<2021.07,>=2.2.0->auto-sklearn) (1.0.1)

In [ ]:
pip install scipy==1.7.1

Requirement already satisfied: scipy==1.7.1 in /usr/local/lib/python3.7/dist-packages (1.7.1)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from scipy==1.7.1) (1.19.5)

In [ ]:
import autosklearn.classification as classifier

In [ ]:
train_data1=pd.read_csv('/content/train.csv')
test_data1=pd.read_csv('/content/test.csv')

In [ ]:
train_data=train_data1.fillna(0)
test_data=test_data1.fillna(0)

In [ ]:
train_data

        id      a     b  c  d      e       f     g        h  i
0     4453  Black  71.0  1  0  fluid  229.73  30.4     Good  0
1     1473  Black  49.0  1  0  solid  139.43  40.2   Normal  0
2     2119  Black  42.0  0  0  solid   68.24  33.1   Normal  0
3     3391  White  53.0  1  0  solid  240.86  31.9     Good  0
4     1000  Black  70.0  1  0  fluid   74.04  29.1     Good  0
...    ...    ...   ... .. ..    ...     ...   ...      ... ..
3572  1402  Black  57.0  0  0  fluid   85.99  21.2  Unknown  0
3573  2927  Black  15.0  0  0  solid  113.28  23.7     Good  0
3574  4937  White  62.0  1  0  solid  103.69  35.2    Worse  0
3575  3001  Black  33.0  0  0  fluid   91.53  38.8   Normal  0
3576  1387  White  37.0  0  0  fluid   98.12  27.5     Good  0

[3577 rows x 10 columns]

In [ ]:
test_data

        id      a     b  c  d      e       f     g        h
0      169  Black  81.0  0  0  fluid   91.54  31.4     Good
1     4022  White  81.0  1  0  solid  181.23  36.7     Good
2     4313  Black  57.0  0  0  solid  134.76  29.1  Unknown
3     1052  White  61.0  0  0  fluid   78.65  36.2   Normal
4     1100  White  67.0  0  0  solid   68.61  31.9     Good
...    ...    ...   ... .. ..    ...     ...   ...      ...
1528   349  White  48.0  0  0  solid  101.41  20.7    Worse
1529  1535  White  55.0  0  0  solid  231.76  42.9     Good
1530  2251  Black  49.0  0  0  solid  130.07  26.0     Good
1531  3801  White  28.0  0  0  solid   69.50  24.5     Good
1532  4141  White  59.0  0  0  fluid   60.64  20.0     Good

[1533 rows x 9 columns]

In [ ]:
loans_one_hot_enc = pd.get_dummies(train_data)

In [ ]:
loans_one_hot_enc

        id     b  c  d       f  ...  e_solid  h_Good  h_Normal  h_Unknown  h_Worse
0     4453  71.0  1  0  229.73  ...        0       1         0          0        0
1     1473  49.0  1  0  139.43  ...        1       0         1          0        0
2     2119  42.0  0  0   68.24  ...        1       0         1          0        0
3     3391  53.0  1  0  240.86  ...        1       1         0          0        0
4     1000  70.0  1  0   74.04  ...        0       1         0          0        0
...    ...   ... .. ..     ...  ...      ...     ...       ...        ...      ...
3572  1402  57.0  0  0   85.99  ...        0       0         0          1        0
3573  2927  15.0  0  0  113.28  ...        1       1         0          0        0
3574  4937  62.0  1  0  103.69  ...        1       0         0          0        1
3575  3001  33.0  0  0   91.53  ...        0       0         1          0        0
3576  1387  37.0  0  0   98.12  ...        0       1         0          0        0

[3577 rows x 16 columns]

In [ ]:
x = loans_one_hot_enc[["b", "c",'d','f','g']]
y = loans_one_hot_enc[["i"]]

In [ ]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.2, random_state = 124)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DecisionTree = DecisionTreeClassifier(criterion='entropy',random_state=2,max_depth=5)
DecisionTree.fit(x_train,y_train)
#predicted_values = DecisionTree.predict(x_test)
x = DecisionTree.score(x_test,y_test)
print("DecisionTrees's Accuracy is: ", x*100)

DecisionTrees's Accuracy is:  94.1340782122905

In [ ]:
from sklearn.naive_bayes import GaussianNB
NaiveBayes = GaussianNB()
NaiveBayes.fit(x_train,y_train)
predicted_values = NaiveBayes.predict(x_test)
x = metrics.accuracy_score(y_test, predicted_values)
print("Naive Bayes's Accuracy is: ", x*100)

Naive Bayes's Accuracy is:  94.1340782122905

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=20, random_state=0)
RF.fit(x_train,y_train)

predicted_values = RF.predict(x_test)

x = metrics.accuracy_score(y_test, predicted_values)

print("Random Forest model Accuracy is: ", x*100)

Random Forest model Accuracy is:  94.1340782122905

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

In [ ]:
sample_test=test_data[["b", "c",'d','f','g']]
sample_test1=test_data[["b"]]

In [ ]:
finaly=DecisionTree.predict(sample_test)

In [ ]:
finaly

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
data = {'id': test_data['id'],
        'i': finaly
        }

df = pd.DataFrame(data)

print (df)

        id  i
0      169  0
1     4022  0
2     4313  0
3     1052  0
4     1100  0
...    ... ..
1528   349  0
1529  1535  0
1530  2251  0
1531  3801  0
1532  4141  0

[1533 rows x 2 columns]

In [ ]:
df

        id  i
0      169  0
1     4022  0
2     4313  0
3     1052  0
4     1100  0
...    ... ..
1528   349  0
1529  1535  0
1530  2251  0
1531  3801  0
1532  4141  0

[1533 rows x 2 columns]

In [ ]:
df.to_csv('file_name.csv')

In [ ]:
nb=NaiveBayes.predict(sample_test1)

In [ ]:
data = {'id': test_data['id'],
        'i': nb
        }

df1 = pd.DataFrame(data)

print (df1)

        id  i
0      169  0
1     4022  0
2     4313  0
3     1052  0
4     1100  0
...    ... ..
1528   349  0
1529  1535  0
1530  2251  0
1531  3801  0
1532  4141  0

[1533 rows x 2 columns]

In [ ]:
df1

        id  i
0      169  0
1     4022  0
2     4313  0
3     1052  0
4     1100  0
...    ... ..
1528   349  0
1529  1535  0
1530  2251  0
1531  3801  0
1532  4141  0

[1533 rows x 2 columns]

In [ ]:
df1.to_csv('file_name1.csv')

In [ ]:
autoclassifier_irrigation_predction=classifier.AutoSklearnClassifier(time_left_for_this_task=180,per_run_time_limit=30)

In [ ]:
autoclassifier_irrigation_predction.fit(x_train,y_train)

[WARNING] [2021-12-23 16:59:35,197:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 1. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:38,485:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 2. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:41,133:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 3. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:43,244:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 4. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:47,925:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 5. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:51,022:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 6. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:54,976:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 7. Number of dummy models: 1
[WARNING] [2021-12-23 16:59:58,295:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 8. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:01,800:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 9. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:04,276:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 10. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:05,736:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 11. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:06,971:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 12. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:10,279:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 13. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:13,666:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 14. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:16,489:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 15. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:17,783:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 16. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:19,124:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 17. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:21,112:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 18. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:22,369:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 19. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:24,924:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 20. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:26,619:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 21. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:27,704:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 22. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:28,773:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 23. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:29,805:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 24. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:35,941:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 25. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:39,093:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 26. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:48,945:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 27. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:55,487:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 28. Number of dummy models: 1
[WARNING] [2021-12-23 17:00:56,810:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 29. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:05,669:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 30. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:14,279:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 31. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:15,671:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 32. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:18,323:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 33. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:19,694:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 34. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:29,901:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 35. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:37,847:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 36. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:46,386:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 37. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:49,650:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 38. Number of dummy models: 1
[WARNING] [2021-12-23 17:01:59,163:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 39. Number of dummy models: 1
[WARNING] [2021-12-23 17:02:11,437:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 40. Number of dummy models: 1
[WARNING] [2021-12-23 17:02:18,870:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 41. Number of dummy models: 1
[WARNING] [2021-12-23 17:02:21,183:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 41. Number of dummy models: 1

AutoSklearnClassifier(per_run_time_limit=30, time_left_for_this_task=180)

In [ ]:
autoclassifier_irrigation_predction.show_models()

"[(1.000000, MyDummyClassifier(config=1,\n                  init_params={'data_preprocessor:feat_type': {'b': 'numerical',\n                                                               'c': 'numerical',\n                                                               'd': 'numerical',\n                                                               'f': 'numerical',\n                                                               'g': 'numerical'},\n                               'instance': None},\n                  random_state=1)),\n]"

In [ ]:
autoclassifier_irrigation_predction.cv_results_['params'][np.argmax(autoclassifier_irrigation_predction.cv_results_['mean_test_score'])]

{'balancing:strategy': 'none',
 'classifier:__choice__': 'mlp',
 'classifier:mlp:activation': 'tanh',
 'classifier:mlp:alpha': 0.004046109807229298,
 'classifier:mlp:batch_size': 'auto',
 'classifier:mlp:beta_1': 0.9,
 'classifier:mlp:beta_2': 0.999,
 'classifier:mlp:early_stopping': 'train',
 'classifier:mlp:epsilon': 1e-08,
 'classifier:mlp:hidden_layer_depth': 3,
 'classifier:mlp:learning_rate_init': 0.00010292125690429162,
 'classifier:mlp:n_iter_no_change': 32,
 'classifier:mlp:num_nodes_per_layer': 17,
 'classifier:mlp:shuffle': 'True',
 'classifier:mlp:solver': 'adam',
 'classifier:mlp:tol': 0.0001,
 'data_preprocessor:__choice__': 'feature_type',
 'data_preprocessor:feature_type:categorical_transformer:categorical_encoding:__choice__': 'one_hot_encoding',
 'data_preprocessor:feature_type:categorical_transformer:category_coalescence:__choice__': 'no_coalescense',
 'data_preprocessor:feature_type:numerical_transformer:imputation:strategy': 'most_frequent',
 'data_preprocessor:feature_type:numerical_transformer:rescaling:__choice__': 'robust_scaler',
 'data_preprocessor:feature_type:numerical_transformer:rescaling:robust_scaler:q_max': 0.7682843015724665,
 'data_preprocessor:feature_type:numerical_transformer:rescaling:robust_scaler:q_min': 0.24100827636041275,
 'feature_preprocessor:__choice__': 'select_percentile_classification',
 'feature_preprocessor:select_percentile_classification:percentile': 88.26404179957224,
 'feature_preprocessor:select_percentile_classification:score_func': 'mutual_info'}

In [ ]:
finaly=autoclassifier_irrigation_predction.predict(sample_test)

In [ ]:
data = {'id': test_data['id'],
        'i': finaly
        }

df = pd.DataFrame(data)

print (df)

        id  i
0      169  0
1     4022  0
2     4313  0
3     1052  0
4     1100  0
...    ... ..
1528   349  0
1529  1535  0
1530  2251  0
1531  3801  0
1532  4141  0

[1533 rows x 2 columns]

In [ ]:
df.to_csv('file_name2.csv')